"""
SENTINEL-X Response Engine

Human-Governed Autonomous SOC response execution engine.
Low-risk events can execute automatically.
Medium/high/critical events require human approval.
"""

from datetime import datetime


def get_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def execute_response(decision, approved=False):
    """
    Execute a security response based on the risk tier.

    Parameters:
        decision (dict): Security decision generated by the playbook engine.
        approved (bool): Human approval for medium/high/critical actions.

    Returns:
        dict: Response execution result.
    """

    if not isinstance(decision, dict):
        return {
            "status": "error",
            "message": "Invalid security decision.",
            "timestamp": get_timestamp()
        }

    risk_tier = str(
        decision.get("risk_tier", "low")
    ).lower()

    action = decision.get(
        "recommended_action",
        "Investigate the event and continue monitoring."
    )

    human_approval_required = decision.get(
        "human_approval_required",
        risk_tier in ["medium", "high", "critical"]
    )

    # ---------------------------------------------------------
    # LOW RISK
    # ---------------------------------------------------------

    if risk_tier == "low":
        return {
            "status": "executed",
            "message": "Low-risk response executed automatically.",
            "risk_tier": risk_tier,
            "recommended_action": action,
            "human_approval_required": False,
            "approved": True,
            "timestamp": get_timestamp()
        }

    # ---------------------------------------------------------
    # MEDIUM / HIGH / CRITICAL
    # ---------------------------------------------------------

    if human_approval_required and not approved:
        return {
            "status": "pending_approval",
            "message": "Human approval is required before response execution.",
            "risk_tier": risk_tier,
            "recommended_action": action,
            "human_approval_required": True,
            "approved": False,
            "timestamp": get_timestamp()
        }

    # ---------------------------------------------------------
    # APPROVED RESPONSE
    # ---------------------------------------------------------

    return {
        "status": "executed",
        "message": "Security response executed after human approval.",
        "risk_tier": risk_tier,
        "recommended_action": action,
        "human_approval_required": True,
        "approved": True,
        "timestamp": get_timestamp()
    }


def approve_response(decision):
    """
    Simulate human approval and execute the recommended response.
    """

    if not isinstance(decision, dict):
        return {
            "status": "error",
            "message": "Invalid security decision.",
            "timestamp": get_timestamp()
        }

    print("\n>>> HUMAN APPROVAL SIMULATION <<<")

    approved_response = execute_response(
        decision,
        approved=True
    )

    return approved_response


def print_response(response):
    """
    Pretty-print a response result.
    """

    print("\n" + "=" * 70)
    print("SENTINEL-X RESPONSE ENGINE")
    print("=" * 70)

    if not isinstance(response, dict):
        print("Response:", response)
        print("=" * 70)
        return

    print("Status:", response.get("status"))
    print("Message:", response.get("message"))
    print("Risk Tier:", response.get("risk_tier"))
    print(
        "Recommended Action:",
        response.get("recommended_action")
    )
    print(
        "Human Approval Required:",
        response.get("human_approval_required")
    )
    print(
        "Approved:",
        response.get("approved")
    )
    print(
        "Timestamp:",
        response.get("timestamp")
    )

    print("=" * 70)


def run_test():
    """
    Test the complete human-governed response flow.
    """

    print("\n")
    print("=" * 70)
    print("SENTINEL-X RESPONSE ENGINE TEST")
    print("=" * 70)

    # ---------------------------------------------------------
    # TEST 1: LOW RISK
    # ---------------------------------------------------------

    low_risk_decision = {
        "risk_tier": "low",
        "recommended_action":
            "Continue monitoring the event.",
        "human_approval_required": False
    }

    print("\n[TEST 1] LOW RISK RESPONSE")

    response = execute_response(
        low_risk_decision,
        approved=False
    )

    print_response(response)

    # ---------------------------------------------------------
    # TEST 2: MEDIUM RISK
    # ---------------------------------------------------------

    medium_risk_decision = {
        "risk_tier": "medium",
        "recommended_action":
            "Investigate the endpoint, isolate the affected host "
            "if the anomaly is confirmed, and continue monitoring.",
        "human_approval_required": True
    }

    print("\n[TEST 2] MEDIUM RISK RESPONSE")

    response = execute_response(
        medium_risk_decision,
        approved=False
    )

    print_response(response)

    # ---------------------------------------------------------
    # HUMAN APPROVAL
    # ---------------------------------------------------------

    print("\n>>> HUMAN APPROVAL SIMULATION <<<")

    approved_response = approve_response(
        medium_risk_decision
    )

    print_response(approved_response)

    # ---------------------------------------------------------
    # TEST 3: HIGH RISK
    # ---------------------------------------------------------

    high_risk_decision = {
        "risk_tier": "high",
        "recommended_action":
            "Disable or restrict the affected account, "
            "revoke suspicious privileges, and investigate.",
        "human_approval_required": True
    }

    print("\n[TEST 3] HIGH RISK RESPONSE")

    response = execute_response(
        high_risk_decision,
        approved=False
    )

    print_response(response)

    # ---------------------------------------------------------
    # HUMAN APPROVAL FOR HIGH RISK
    # ---------------------------------------------------------

    print("\n>>> HUMAN APPROVAL SIMULATION <<<")

    approved_response = approve_response(
        high_risk_decision
    )

    print_response(approved_response)

    # ---------------------------------------------------------
    # TEST 4: CRITICAL RISK
    # ---------------------------------------------------------

    critical_risk_decision = {
        "risk_tier": "critical",
        "recommended_action":
            "Immediately contain the affected host, "
            "block suspicious outbound traffic, "
            "and initiate incident response.",
        "human_approval_required": True
    }

    print("\n[TEST 4] CRITICAL RISK RESPONSE")

    response = execute_response(
        critical_risk_decision,
        approved=False
    )

    print_response(response)

    # ---------------------------------------------------------
    # HUMAN APPROVAL FOR CRITICAL RESPONSE
    # ---------------------------------------------------------

    print("\n>>> HUMAN APPROVAL SIMULATION <<<")

    approved_response = approve_response(
        critical_risk_decision
    )

    print_response(approved_response)

    print("\n")
    print("=" * 70)
    print("RESPONSE ENGINE TEST COMPLETED")
    print("=" * 70)


if __name__ == "__main__":
    run_test()